### ISSUE TITLE
string-join missing on GNU Emacs 24.5.1?

### ISSUE THREAD

**Issue by thsutton** [david-christiansen/jonprl-mode#18]
I received errors about string-join's definition being void or some such until I made the following change to `jonprl-mode.el`. I have no idea if this is correct, but the error stopped happening and I seem to have some more functionality:

```
diff --git a/jonprl-mode.el b/jonprl-mode.el
index 088399c..ca8a1ce 100644
--- a/jonprl-mode.el
+++ b/jonprl-mode.el
@@ -27,6 +27,7 @@

 ;;; Code:
 (require 'compile)
+(require 'subr-x)
 (require 'cl-lib)
 (require 'yasnippet)
```

**Comment by david-christiansen** [comment]
Thanks for the report!
