### ISSUE TITLE
Highlighting for (* comments *)

### ISSUE THREAD

**Issue by jonsterling** [david-christiansen/jonprl-mode#19]
Reported by Vincent Rahli (of the PRL group)

**Comment by david-christiansen** [comment]
I didn't know JonPRL had that. I'll throw it together.

**Comment by jonsterling** [comment]
thanks! I wasn't sure how to do it, or I'd just do it myself :)

**Comment by david-christiansen** [comment]
The syntax table is one of the crustier bits of Emacs :-)
